configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/rye%2Fcheckout-intents-27ace1b83143cb23fae0ce2a07709399b9c1d9eeffaac8db4ccf3228e10e4a7b.yml
openapi_spec_hash: bb5f9b3e1ecadae10a7afba827a2d234
config_hash: 544bc1c626b5c2e54957b7edeb484916
